Traceback (most recent call last):
  File "benchmark_gpu.py", line 55, in <module>
    H, edges = pp.joint_pdf(w_norm, DI_c, bins=bins, ranges=ranges, log=False)
  File "/mnt/beegfs/home/allaglo/sfemans_ai/nikita/gpu_source/stats.py", line 122, in joint_pdf
    H, xedges, yedges = cp.histogram2d(field1, field2, bins=bins, range=ranges, \
  File "/mnt/beegfs/home/allaglo/miniconda3/envs/statistics/lib/python3.8/site-packages/cupy/_statistics/histogram.py", line 502, in histogram2d
    hist, edges = histogramdd([x, y], bins, range, weights, density)
  File "/mnt/beegfs/home/allaglo/miniconda3/envs/statistics/lib/python3.8/site-packages/cupy/_statistics/histogram.py", line 417, in histogramdd
    xy = cupy.ravel_multi_index(ncount, nbin)
  File "/mnt/beegfs/home/allaglo/miniconda3/envs/statistics/lib/python3.8/site-packages/cupy/_indexing/generate.py", line 364, in ravel_multi_index
    raveled_indices += stride * idx
  File "cupy/_core/core.pyx", line 1698, in cupy._core.core._ndarray_base.__array_ufunc__
  File "cupy/_core/_kernel.pyx", line 1351, in cupy._core._kernel.ufunc.__call__
  File "cupy/_core/_kernel.pyx", line 646, in cupy._core._kernel._get_out_args_from_optionals
  File "cupy/_core/core.pyx", line 2787, in cupy._core.core._ndarray_init
  File "cupy/_core/core.pyx", line 241, in cupy._core.core._ndarray_base._init_fast
  File "cupy/cuda/memory.pyx", line 742, in cupy.cuda.memory.alloc
  File "cupy/cuda/memory.pyx", line 1419, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1440, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1120, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1141, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc
  File "cupy/cuda/memory.pyx", line 1379, in cupy.cuda.memory.SingleDeviceMemoryPool._try_malloc
cupy.cuda.memory.OutOfMemoryError: Out of memory allocating 3,513,686,528 bytes (allocated so far: 49,660,139,520 bytes).
